### ISSUE TITLE
Remove second "percent" value from Campaign Tabs when the base metric is a percent

### ISSUE THREAD

**Issue by DillonMorrison** [looker/app-marketing#34]
fairly self explanatory. See Screenshot below. The second percent value just doesn't help (even though it's technically accurate)

**Comment by DillonMorrison** [comment]
<img width="1133" alt="screen shot 2018-12-04 at 5 07 13 pm" src="https://user-images.githubusercontent.com/9888083/49483276-6cd1e080-f7e7-11e8-8fe4-5b766d8b92f6.png">

**Comment by AnnaSerova** [comment]
moving this to Luke's board
